export type SelfPrAnswers = {
  achievementTitle: string;
  situation: string;
  task: string;
  action: string;
  result: string;
  metrics?: string;
  strength1: string;
  example1: string;
  strength2: string;
  example2: string;
  strength3: string;
  example3: string;
  bestFit: string;
  avoid?: string;
  principle1?: string;
  principle2?: string;
  principle3?: string;
  futureTarget: string;
  futureValue: string;
  futureLevel: string;
  futureProof?: string;
};
